catalogMode: prefer
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - undici@5.29.0
  - undici-types@6.21.0

packages:
  - packages/*

catalog:
  '@actions/core': ^2.0.2
  '@actions/github': ^9.0.0
  '@antfu/eslint-config': ^7.2.0
  '@octokit/plugin-rest-endpoint-methods': ^17.0.0
  '@types/node': ^24.10.9
  eslint: ^9.39.2
  tsdown: ^0.20.1
