catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - actions/*
  - packages/*
catalog:
  '@actions/core': ^3.0.1
  '@actions/exec': ^3.0.0
  '@actions/github': ^9.1.1
  '@antfu/eslint-config': ^9.0.0
  '@octokit/plugin-rest-endpoint-methods': ^17.0.0
  '@types/node': ^24.13.2
  '@typescript/native-preview': 7.0.0-dev.20260620.1
  eslint: ^10.5.0
  tsdown: ^0.22.3
  vitest: ^4.1.9
