name: Close Release Issues
description: Close issues with release label when merging release branch

inputs:
  branch-name:
    description: The branch name to check and close issues for (e.g. release/1.2.3)
    required: true

runs:
  using: node24
  main: ../packages/close-release-issue/dist/index.mjs
