name: Setup Flutter
description: Setup Flutter environment

inputs:
  flutter-version:
    description: The Flutter version to use
    required: true
    default: 3.x
  channel:
    description: The Flutter channel to use
    required: false
    default: stable
  cache:
    description: Enable caching for Flutter SDK and packages
    required: false
    default: true
  aop-registry:
    description: Use AOP registry for Flutter packages
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2.21.0
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: ${{ inputs.channel }}
        cache: ${{ inputs.cache }}

    - name: AOP Registry
      if: ${{ inputs.aop-registry }}
      shell: bash
      run: |
        set -e
        echo "Setting up AOP registry for Flutter packages..."
