name: Setup Flutter
description: Setup Flutter environment

inputs:
  flutter-version:
    description: The Flutter version to use
    required: true
    default: 3.x
  channel:
    description: The Flutter channel to use
    required: false
    default: stable
  cache:
    description: Enable caching for Flutter SDK and packages
    required: false
    default: 'false'
  aop-registry:
    description: Use AOP registry for Flutter packages
    required: false
    default: 'false'
  aop-project-path:
    description: The path to the AOP project
    required: false
  aop-repo:
    description: The URL of the AOP repository
    required: false
    default: 'https://github.com/TDesignOteam/tdesign-flutter-aop-registry.git'
  aop-repo-branch:
    description: The branch of the AOP repository
    required: false
    default: main

runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2.21.0
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: ${{ inputs.channel }}
        cache: ${{ inputs.cache }}

    - name: Download AOP Tools
      if: ${{ inputs.aop-registry == 'true' }}
      shell: bash
      run: |
        cd ${{ runner.temp }}
        git clone ${{ inputs.aop-repo }} -b ${{ inputs.aop-repo-branch }}
        git clone https://github.com/TDesignOteam/tdesign-flutter-generator.git

    - name: Move aop_tools to ${{ inputs.aop-project-path }}
      if: ${{ inputs.aop-registry == 'true' }}
      shell: bash
      run: |
        cp -af ${{ runner.temp }}/tdesign-flutter-aop-registry/_example/aop_tools ${{ inputs.aop-project-path }}
        ls -l ${{ inputs.aop-project-path }}/aop_tools

    - name: Move generator to ${{ inputs.aop-project-path }}
      if: ${{ inputs.aop-registry == 'true' }}
      shell: bash
      run: |
        cp -af ${{ runner.temp }}/tdesign-flutter-generator ${{ inputs.aop-project-path }}
        ls -l ${{ inputs.aop-project-path }}/tdesign-flutter-generator

    - name: AOP Registry
      if: ${{ inputs.aop-registry == 'true' }}
      shell: bash
      run: |
        set -eu
        echo "Setting up AOP registry for Flutter packages..."
        echo "Entering Flutter root directory"
        cd ${{ env.FLUTTER_ROOT }}
        pwd
        echo "Checking git status"
        git status
        echo "Restoring working directory"
        git restore .
        echo "Cleaning working directory"
        git clean -fd
        echo "检查 git 状态"
        git status

        rm ./bin/cache/flutter_tools.stamp
        flutter --version

        aop_patch_path="${{ runner.temp }}/tdesign-flutter-aop-registry/patch_flutter"
        flutter_version=$(flutter --version | head -n 1 | awk '{print $2}')
        major_version=$(echo $flutter_version | cut -d. -f1)
        minor_version=$(echo $flutter_version | cut -d. -f2)

        # 确定适用的补丁文件
        # 2.2~3.10.patch, 3.13~3.16.patch, 3.19~3.22.patch, 3.24~3.27.patch, 3.29~3.32.patch, 3.35.patch, 3.38~infinity.patch
        case "$major_version.$minor_version" in
          4.*|3.3[89]|3.[4-9][0-9])
            # 3.38+ 及更高版本
            patch_name="3.38~infinity.patch"
            ;;
          3.35)
            # 3.35
            patch_name="3.35.patch"
            ;;
          3.29|3.3[0-2])
            # 3.29-3.32
            patch_name="3.29~3.32.patch"
            ;;
          3.2[4-7])
            # 3.24-3.27
            patch_name="3.24~3.27.patch"
            ;;
          3.19|3.2[0-2])
            # 3.19-3.22
            patch_name="3.19~3.22.patch"
            ;;
          3.1[3-6])
            # 3.13-3.16
            patch_name="3.13~3.16.patch"
            ;;
          2.[2-9]|3.0[0-9]|3.1[01])
            # 2.2-3.10
            patch_name="2.2~3.10.patch"
            ;;
          *)
            echo "Error: No patch available for Flutter $flutter_version"
            exit 1
            ;;
        esac
        echo "patch_name: $patch_name"
        echo "aop_patch_path: $aop_patch_path"
        patch="$aop_patch_path/$patch_name"
        echo "patch: $patch"
        git status
        git apply $patch
        git status

        # 删除SDK/bin/cache/flutter_tools.stamp，使修改生效
        rm ./bin/cache/flutter_tools.stamp

        echo "AOP registry setup completed."
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        flutter --version
