import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: ['index.ts'],
  shims: true,
  deps: {
    alwaysBundle: [
      '@actions/core',
      '@actions/exec',
      '@actions/github',
      '@workflows/utils',
      '@pnpm/workspace.manifest-writer',
      '@pnpm/workspace.read-manifest',
    ],
    onlyBundle: [
      '@actions/core',
      '@actions/exec',
      '@actions/github',
      '@actions/http-client',
      '@actions/io',
      '@octokit/auth-token',
      '@octokit/core',
      '@octokit/endpoint',
      '@octokit/graphql',
      '@octokit/plugin-paginate-rest',
      '@octokit/plugin-rest-endpoint-methods',
      '@octokit/request',
      '@octokit/request-error',
      '@pnpm/constants',
      '@pnpm/error',
      '@pnpm/object.key-sorting',
      '@pnpm/ramda',
      '@pnpm/util.lex-comparator',
      '@pnpm/workspace.manifest-writer',
      '@pnpm/workspace.read-manifest',
      '@pnpm/yaml.document-sync',
      'before-after-hook',
      'fast-content-type-parse',
      'imurmurhash',
      'is-plain-obj',
      'js-yaml',
      'read-yaml-file',
      'signal-exit',
      'sort-keys',
      'strip-bom',
      'tunnel',
      'undici',
      'universal-user-agent',
      'write-file-atomic',
      'yaml',
    ],
  },
})
