name: pr-spell-check
on:
  - pull_request

jobs:
  call-check:
    uses: TDesignOteam/workflows/.github/workflows/reusable-spell-check.yml@26aafb4b9b9a3e9ebd030d89c1a1ff2436c4781e # main
    with:
      config: .github/workflows/typos-config.toml
