name: pr-spell-check
on:
  - pull_request

jobs:
  call-check:
    uses: TDesignOteam/workflows/.github/workflows/reusable-spell-check.yml@9aef33d891b5595ba7fecab0de1bf6d67dd9aaaf # main
    with:
      config: .github/workflows/typos-config.toml
