# 将仓库同步到 CNB (cnb.cool)，push 时同步代码，delete 时删除对应分支
name: reusable-cnb-sync

on:
  workflow_call:
    inputs:
      github-repo:
        required: true
        type: string
        description: GitHub 仓库路径，如 TDesignOteam/tdesign-api
      cnb-repo:
        required: true
        type: string
        description: CNB 仓库路径，如 tencent/tdesign/tdesign-api
    secrets:
      CNB_TOKEN:
        required: true

jobs:
  sync-push:
    if: ${{ inputs.github-repo == github.repository && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: docker://tencentcom/git-sync@sha256:b7c4672616ddea5b89948dcd034610b29d37d8430e74b4bc83b421c963c25f77
        env:
          PLUGIN_TARGET_URL: https://cnb.cool/${{ inputs.cnb-repo }}.git
          PLUGIN_AUTH_TYPE: https
          PLUGIN_USERNAME: cnb
          PLUGIN_PASSWORD: ${{ secrets.CNB_TOKEN }}
          PLUGIN_FORCE: 'true'

  sync-delete-branch:
    if: ${{ inputs.github-repo == github.repository && github.event_name == 'delete' && github.event.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: TDesignOteam/workflows/actions/cnb-delete-branch@83293c1063bcb1af6e91e2e9c7d6a9dd3b69089f # main
        with:
          repo: ${{ inputs.cnb-repo }}
          token: ${{ secrets.CNB_TOKEN }}
          branch: ${{ github.event.ref }}
