name: reusable-unit-test
on:
  workflow_call:
    inputs:
      skip-site:
        required: false
        type: boolean
        default: false
      node-version:
        required: false
        type: string
        default: '22'
      node-version-file:
        required: false
        type: string
        default: ''
      package-manager:
        required: false
        type: string
        default: npm

jobs:
  check-email:
    runs-on: ubuntu-latest
    steps:
      - uses: TDesignOteam/workflows/actions/check-email@main

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4.2.0
        if: ${{ inputs.package-manager == 'pnpm' }}

      - uses: actions/setup-node@v6.3.0
        with:
          node-version: ${{ inputs.node-version-file && '' || inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}

      - run: ${{ inputs.package-manager }} install

      - run: ${{ inputs.package-manager }} run lint
      - run: ${{ inputs.package-manager }} run test
      # upload report to codecov
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  site:
    if: ${{ !inputs.skip-site }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4.2.0
        if: ${{ inputs.package-manager == 'pnpm' }}

      - uses: actions/setup-node@v6.3.0
        with:
          node-version: ${{ inputs.node-version-file && '' || inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}

      - run: ${{ inputs.package-manager }} install

      - name: Build site
        run: ${{ inputs.package-manager }} run site:preview

      - run: |
          zip -r _site.zip _site

      - name: upload _site artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: _site
          path: _site.zip
          retention-days: 5

      - name: Save PR number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > ./pr-id.txt

      - name: Upload PR number
        if: ${{ always() }}
        uses: actions/upload-artifact@v7.0.0
        with:
          name: pr
          path: ./pr-id.txt

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4.2.0
        if: ${{ inputs.package-manager == 'pnpm' }}

      - uses: actions/setup-node@v6.3.0
        with:
          node-version: ${{ inputs.node-version-file && '' || inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}

      - run: ${{ inputs.package-manager }} install

      - name: Build
        run: ${{ inputs.package-manager }} run build
