name: reusable-publish-npm

on:
  workflow_call:
    secrets:
      TDESIGN_BOT_TOKEN:
        required: false

      TDESIGN_SURGE_TOKEN:
        required: true

    inputs:
      node-version:
        required: false
        type: string
        default: '22'

      node-version-file:
        required: false
        type: string
        default: ''

      package-manager:
        required: false
        type: string
        default: npm

      surge-token:
        required: false
        type: string

      token:
        required: false
        type: string
        default: ${{ github.token }}

      skip-publish-npm:
        required: false
        type: boolean
        default: false

      skip-publish-tag-website:
        required: false
        type: boolean
        default: false

      skip-publish-official-website:
        required: false
        type: boolean
        default: false

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag' && !inputs.publish-npm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ inputs.node-version-file == '' && inputs.node-version || null }}
          node-version-file: ${{ inputs.node-version-file != '' && inputs.node-version-file || null }}

      - run: ${{ inputs.package-manager }} install

      - run: ${{ inputs.package-manager }} run build

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24

      - id: tag
        shell: bash
        run: |
          tag=${{ contains(github.ref_name, 'beta') && 'beta' || 'latest' }}
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: npm publish
        if: ${{ inputs.package-manager  == 'npm'}}
        uses: JS-DevTools/npm-publish@0fd2f4369c5d6bcfcde6091a7c527d810b9b5c3f # v4
        with:
          tag: ${{ steps.tag.outputs.tag }}

      - name: pnpm publish
        if: ${{ inputs.package-manager  == 'pnpm'}}
        run: pnpm publish --access public --no-git-checks --tag ${{ steps.tag.outputs.tag }}

  publish-tag-website:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag' && !inputs.publish-tag-website
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        if: ${{ inputs.package-manager == 'pnpm' }}

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ inputs.node-version-file == '' && inputs.node-version || null }}
          node-version-file: ${{ inputs.node-version-file != '' && inputs.node-version-file || null }}

      - run: ${{ inputs.package-manager }} install

      - run: ${{ inputs.package-manager }} run site:preview

      - id: domain
        shell: bash
        run: |
          repository=${{github.repository}}
          project_name=${repository#*/}
          ref_name=${{ github.ref_name }}
          tag_name=${ref_name//./_}
          echo "domain=https://$tag_name-$project_name.surge.sh" >> $GITHUB_OUTPUT

      - uses: TDesignOteam/workflows/actions/setup-surge@9aef33d891b5595ba7fecab0de1bf6d67dd9aaaf # main
        with:
          project: _site
          domain: ${{ steps.domain.outputs.domain }}
          token: ${{ secrets.TDESIGN_SURGE_TOKEN }}

  publish-official-website:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag' && !inputs.publish-official-website
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          submodules: recursive

      - name: update official website
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git status
          git fetch origin
          git merge origin/develop
          git push origin main
