# 将仓库同步到 CNB (cnb.cool)，push 时同步代码，delete 时删除对应分支
name: reusable-cnb-sync

on:
  workflow_call:
    inputs:
      github-repo:
        required: true
        type: string
        description: GitHub 仓库路径，如 TDesignOteam/tdesign-api
      cnb-repo:
        required: true
        type: string
        description: CNB 仓库路径，如 tencent/tdesign/tdesign-api
    secrets:
      CNB_TOKEN:
        required: true

jobs:
  sync-push:
    if: ${{ inputs.github-repo == github.repository && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: docker://tencentcom/git-sync@sha256:233c89bd41472ea530322509cc624604ac6c3cc566feebdfbab66d827aac73b7
        env:
          PLUGIN_TARGET_URL: https://cnb.cool/${{ inputs.cnb-repo }}.git
          PLUGIN_AUTH_TYPE: https
          PLUGIN_USERNAME: cnb
          PLUGIN_PASSWORD: ${{ secrets.CNB_TOKEN }}
          PLUGIN_FORCE: 'true'

  sync-delete-branch:
    if: ${{ inputs.github-repo == github.repository && github.event_name == 'delete' && github.event.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: TDesignOteam/workflows/actions/cnb-delete-branch@2c83bb5eec2aa598759e8ce57f0af326ed022056 # main
        with:
          repo: ${{ inputs.cnb-repo }}
          token: ${{ secrets.CNB_TOKEN }}
          branch: ${{ github.event.ref }}
