# 当打上 easy/middle/hard 标签时，追加难度分级模板
name: reusable-issue-shoot

on:
  workflow_call:
    inputs:
      issue-number:
        required: false
        type: number
        default: ${{ github.event.issue.number }}
      template-path:
        required: false
        type: string
        default: .github/issue-shoot.md

jobs:
  add-template:
    if: contains(fromJSON('["easy", "middle", "hard"]'), github.event.label.name)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          sparse-checkout: |
            .github

      - name: Get level config
        id: config
        run: |
          label=${{ github.event.label.name }}
          if [[ $label = "easy" ]]
          then
            echo "level=低" >> $GITHUB_OUTPUT
            echo "duration=1" >> $GITHUB_OUTPUT
            echo "deadline=$(date -d '+3 days' +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          elif [[ $label = "middle" ]]
          then
            echo "level=中" >> $GITHUB_OUTPUT
            echo "duration=3" >> $GITHUB_OUTPUT
            echo "deadline=$(date -d '+7 days' +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          else
            echo "level=高" >> $GITHUB_OUTPUT
            echo "duration=5" >> $GITHUB_OUTPUT
            echo "deadline=$(date -d '+10 days' +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          fi

      - name: Render template
        id: template
        uses: chuhlomin/render-template@a7c644e341797d050d1cb24332d83791b9a46dae # v1.12
        with:
          template: ${{ inputs.template-path }}
          vars: |
            level: ${{ steps.config.outputs.level }}
            duration: ${{ steps.config.outputs.duration }}
            deadline: ${{ steps.config.outputs.deadline }}

      - name: Update issue
        uses: TDesignOteam/workflows/actions/issues-helper@d6f2ca72bb123b158ee978858591165a57cb446a # main
        with:
          actions: update-issue
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ inputs.issue-number }}
          body: ${{ steps.template.outputs.result }}
          update-mode: append
