name: test-close-release-issue
on:
  pull_request:
    branches:
      - main
    paths:
      - actions/close-release-issue/dist/*

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: test
        uses: ./actions/close-release-issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
