name: test-upgrade-deps
on:
  pull_request:
    branches:
      - main
    paths:
      - packages/upgrade-deps/dist/*

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-node@v6.3.0

      - name: test
        uses: ./actions/upgrade-deps
        with:
          token: test
          dry-run: true
          repo: tdesign-vue
          owner: Tencent
          deps: |
            '@tdesign/site-components'
            '@tdesign/theme-generator'
