name: test-upgrade-deps
on:
  pull_request:
    branches:
      - main
    paths:
      - packages/test-upgrade-deps/dist/*

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: test
        uses: ./actions/upgrade-deps
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
          repo: tdesign-vue
          owner: Tencent
          deps:
            - '@tdesign/site-components'
